{% set name = "catkin_tools" %}
{% set version = "0.9.0" %}
{% set sha256 = "1ded682e4c13ef9aef97ff12472357418eb0c1581db5c319d2594162bfc18652" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/catkin/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - catkin_pkg >=0.3.0
    - make
    - pyyaml
    - psutil
    - osrf_pycommon >0.1.1
    - coreutils

test:
  commands:
    - catkin --help
    - catkin init --help
    - catkin build --help
    - catkin list --help
    - catkin env --help
about:
  home: https://catkin-tools.readthedocs.io/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: This Python package provides command line tools for working with the catkin meta-buildsystem and catkin workspaces.
  dev_url: https://github.com/catkin/catkin_tools

extra:
  recipe-maintainers:
    - wolfv
    - lesteve
    - Tobias-Fischer
