{% set name = "catkin_tools" %}
{% set version = "0.9.4" %}
{% set sha256 = "5b6e1867b0e82b7a69b847be170d808074f6b817c44766d261bca55856475647" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/catkin/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - catkin_pkg >=0.3.0
    - make
    - pyyaml
    - psutil
    - osrf_pycommon >0.1.1
    - coreutils

test:
  requires:
    - python {{ python_min }}
  commands:
    - catkin --help
    - catkin init --help
    - catkin build --help
    - catkin list --help
    - catkin env --help
about:
  home: https://catkin-tools.readthedocs.io/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: This Python package provides command line tools for working with the catkin meta-buildsystem and catkin workspaces.
  dev_url: https://github.com/catkin/catkin_tools

extra:
  recipe-maintainers:
    - wolfv
    - Tobias-Fischer
