{% set name = "catkin_tools" %}
{% set version = "0.5.0" %}
{% set sha256 = "cb7bc63c52033428e3514d9b7372f8303f7a68e56a5401b3e9eba338a7de5bb8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/catkin/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - remove_trollius.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [win]

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - catkin_pkg >0.2.9
    - pyyaml
    - psutil
    - osrf_pycommon >0.1.1
    - trollius  # [py < 34]

test:
  commands:
    - catkin --help
    - catkin init --help
    - catkin build --help
    - catkin list --help
    - catkin env --help
about:
  home: https://catkin-tools.readthedocs.io/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: This Python package provides command line tools for working with the catkin meta-buildsystem and catkin workspaces.
  dev_url: https://github.com/catkin/catkin_tools

extra:
  recipe-maintainers:
    - wolfv
    - lesteve
